version: "2.0"

services:
  redis7000:
    image: redis
    hostname: redis-7000
    container_name: redis-7000
    volumes:
      - ./volumes/7000/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7000:7000
    networks:
      redis-net:
        ipv4_address: 172.20.1.2
    command: #sh -c 'redis-server /usr/local/etc/redis/redis.conf && echo yes | redis-cli --cluster create 172.18.1.2:7000 172.18.1.3:7001 172.18.1.4:7002 172.18.1.5:7003 172.18.1.6:7004 172.18.1.7:7005 --cluster-replicas 1 -a vox123'
      - redis-server
      - /usr/local/etc/redis/redis.conf
 
  redis7001:
    image: redis
    hostname: redis-7001
    container_name: redis-7001
    networks:
      redis-net:
        ipv4_address: 172.20.1.3
    volumes:
      - ./volumes/7001/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7001:7001
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
  
  redis7002:
    image: redis
    hostname: redis-7002
    container_name: redis-7002
    networks:
      redis-net:
        ipv4_address: 172.20.1.4
    volumes:
      - ./volumes/7002/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7002:7002
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  redis7003:
    image: redis
    hostname: redis-7003
    container_name: redis-7003
    networks:
      redis-net:
        ipv4_address: 172.20.1.5
    volumes:
      - ./volumes/7003/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7003:7003
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  redis7004:
    image: redis
    hostname: redis-7004
    container_name: redis-7004
    networks:
      redis-net:
        ipv4_address: 172.20.1.6
    volumes:
      - ./volumes/7004/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7004:7004
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  redis7005:
    image: redis
    hostname: redis-7005
    container_name: redis-7005
    networks:
      redis-net:
        ipv4_address: 172.20.1.7
    volumes:
      - ./volumes/7005/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7005:7005
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1
