version: "2.0"

services:
  redis7000:
    image: redis
    hostname: redis-7000
    container_name: redis-7000
    volumes:
      - /Users/cielleech/Documents/workspace/docker/vox-docker/volumes/redis-cluster/7000/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7000:7000
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf


  redis7001:
    image: redis
    hostname: redis-7001
    container_name: redis-7001
    volumes:
      - /Users/cielleech/Documents/workspace/docker/vox-docker/volumes/redis-cluster/7001/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7001:7001
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
  
  redis7002:
    image: redis
    hostname: redis-7002
    container_name: redis-7002
    volumes:
      - /Users/cielleech/Documents/workspace/docker/vox-docker/volumes/redis-cluster/7002/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7002:7002
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  redis7003:
    image: redis
    hostname: redis-7003
    container_name: redis-7003
    volumes:
      - /Users/cielleech/Documents/workspace/docker/vox-docker/volumes/redis-cluster/7003/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7003:7003
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  redis7004:
    image: redis
    hostname: redis-7004
    container_name: redis-7004
    volumes:
      - /Users/cielleech/Documents/workspace/docker/vox-docker/volumes/redis-cluster/7004/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7004:7004
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  redis7005:
    image: redis
    hostname: redis-7005
    container_name: redis-7005
    volumes:
      - /Users/cielleech/Documents/workspace/docker/vox-docker/volumes/redis-cluster/7005/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7005:7005
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf