version: '2'

services:
  zoo1:
    image: zookeeper:3.4.11
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
    networks:
      zk-net:
        ipv4_address: 10.6.0.2
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      
      
  zoo2:
    image: zookeeper:3.4.11
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2182:2181
    networks:
     zk-net:
       ipv4_address: 10.6.0.3
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
      
      
  zoo3:
    image: zookeeper:3.4.11
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2183:2181
    networks:
      zk-net:
        ipv4_address: 10.6.0.4
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
      
networks:
  zk-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
