version: '2.2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch1
    environment:
      - cluster.name="docker-cluster"
      - node.name="elasticsearch1"
      - node.master=true
      - node.data=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.ping.unicast.hosts="elasticsearch1,elasticsearch2,elasticsearch3,elasticsearch4"
      - discovery.zen.minimum_master_nodes=1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch2
    environment:
      - cluster.name="docker-cluster"
      - node.name="elasticsearch2"
      - node.master=false
      - node.data=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.ping.unicast.hosts="elasticsearch1,elasticsearch2,elasticsearch3,elasticsearch4"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch3
    environment:
      - cluster.name="docker-cluster"
      - node.name="elasticsearch3"
      - node.master=false
      - node.data=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*      
      - discovery.zen.ping.unicast.hosts="elasticsearch1,elasticsearch2,elasticsearch3,elasticsearch4"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch4:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch4
    environment:
      - cluster.name="docker-cluster"
      - node.name="elasticsearch4"
      - node.master=false
      - node.data=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*      
      - discovery.zen.ping.unicast.hosts="elasticsearch1,elasticsearch2,elasticsearch3,elasticsearch4"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata4:/usr/share/elasticsearch/data
    networks:
      - esnet      

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  esdata4:
    driver: local

networks:
  esnet:
