version: "3.3"

services:
  vox-mysql:
    image: mysql:5.7.20
    hostname: vox-mysql
    container_name: vox-mysql
    networks:
      default:
        ipv4_address: 172.18.0.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=vox123
    ports:
      - 3306:3306
    volumes:
      - ./volumes/data:/var/lib/mysql

networks:
  default:
    external:
      name: base-net
