version: '3'

services:
  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    external_links:
      - namenode:namenode
      - datanode:datanode
    networks:
      default:
        ipv4_address: 172.18.1.40
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hbase-standalone.env

volumes:
  hbase_data:
  hbase_zookeeper_data:

networks:
  default:
    external:
      name: base-net