version: '2'

services:
  zoo:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo
    networks:
      default:
        ipv4_address: 172.18.1.3
    ports:
      - "2181:2181"
    container_name: zookeeper

  # kafka version: 1.1.0
  # scala version: 2.12
  kafka:
    image: wurstmeister/kafka
    networks:
      default:
        ipv4_address: 172.18.1.4
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    depends_on:
      - zoo
    container_name: kafka


networks:
  default:
    external:
      name: base-net