version: "2.0"

services:
  redis:
    image: redis
    hostname: redis-6379
    container_name: redis-6379
    volumes:
      - ./volumes/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      redis-net:
        ipv4_address: 172.18.1.102
    command: #sh -c 'redis-server /usr/local/etc/redis/redis.conf && echo yes | redis-cli --cluster create 172.18.1.2:7000 172.18.1.3:7001 172.18.1.4:7002 172.18.1.5:7003 172.18.1.6:7004 172.18.1.7:7005 --cluster-replicas 1 -a vox123'
      - redis-server
      - /usr/local/etc/redis/redis.conf


networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1
